### ISSUE TITLE
Error with invalid format string

### ISSUE THREAD

**Issue by skibum1869** [pkout/yahoo_finance_api2#1]
I attempted to use the api on python 3.6.8 and received the following when executing the following code.

`>>> import sys
>>> from yahoo_finance_api2 import share
>>> from yahoo_finance_api2.exceptions import YahooFinanceError

>>> dataset = share.Share('NBR')
>>> symbol_data = None
>>>
>>> try:
...     symbol_data = dataset.get_historical(share.PERIOD_TYPE_DAY,
...                                          10,
...                                          share.FREQUENCY_TYPE_MINUTE,
...                                          5)
... except YahooFinanceError as e:
...     print(e.message)
...     sys.exit(1)`

returned the following error

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "C:\Users\maxic\AppData\Local\Programs\Python\Python36\lib\site-packages\yahoo_finance_api2\share.py", line 26, in get_historical
    frequency_type, frequency)
  File "C:\Users\maxic\AppData\Local\Programs\Python\Python36\lib\site-packages\yahoo_finance_api2\share.py", line 84, in _download_symbol_data
    start_time, end_time = self._set_time_frame(period_type, period)
  File "C:\Users\maxic\AppData\Local\Programs\Python\Python36\lib\site-packages\yahoo_finance_api2\share.py", line 79, in _set_time_frame
    return start_time.strftime("%s"), end_time.strftime("%s")
ValueError: Invalid format string

**Comment by pkout** [comment]
Hi Max,

I'll look into it tonight when I get home from work. I'll let you know.

Thanks,
Petr

**Comment by pkout** [comment]
Hi Max,

Sorry, I didn't get to this until now. I tried to run your code above and
it worked fine. I wonder if there was some issue related to the specific
day when you ran it. Can you try to run it again and let me know if it
fails again?

Thanks!
Petr

**Comment by skibum1869** [comment]
Sorry for just getting back to you but it still had the same error when trying it. 
Below is the code that I am trying to run in case there are issues in the code.

[main.zip](https://github.com/pkout/yahoo_finance_api2/files/3180045/main.zip)
