### ISSUE TITLE
"get_historical()" issue

### ISSUE THREAD

**Issue by Sinha-Ujjawal** [pkout/yahoo_finance_api2#3]
Hi,

I made a helper function that will give me the stock prices based on the ticker, which internally calls your api. I am getting daily data for "NSANY" for 10 years, sometimes the api returns data from 2009 and sometimes it returns data from 2018.

Helper code-

``` python
def datetime_from_timestamp(timestamp):
    x = datetime.fromtimestamp(int(str(timestamp)[:-3]))
    return pd.datetime(
        x.year, x.month, x.day,
        x.hour, x.minute, x.second, x.microsecond,
        x.tzinfo
    )

def get_share_data(share_name, period_type, period, frequency_type, frequency):
    s = share.Share(share_name)
    try:
        data = s.get_historical(
            period_type, period,
            frequency_type, frequency
        )
        df = pd.DataFrame()
        
        df['open']   = data['open']
        df['high']   = data['high']
        df['low']    = data['low']
        df['close']  = data['close']
        df['volume'] = data['volume']
        
        df.index     = list(
            map(
                datetime_from_timestamp,
                data['timestamp']
            )
        )
        
        return df
        
    except Exception as e:
        print(e)
        pass
```

**Comment by pkout** [comment]
NSANY has been listed in the stock exchange since last year only. I am not sure how Yahoo handles a query that asks for 10 years of historical data when only 1 year of data exists. That behavior might be undefined, which might be why you're seeing strange results.

**Comment by Sinha-Ujjawal** [comment]
@pkout Ok, but sometimes it gives me the data from 2009 and sometimes from 2018. What's that supposed to mean? Isn't the API should always return me the same thing for the same request.
